## Stage 1 - Go Build Env
FROM golang:1.25-alpine AS build

RUN apk add --no-cache gcc libc-dev musl-dev curl npm wget
RUN npm install --global yarn

ENV GOPROXY https://proxy.golang.org
ENV CGO_ENABLED 0

RUN mkdir -p /src/mc-web-console-front
WORKDIR /src/mc-web-console-front
ADD ./front .

RUN go mod download
RUN npm install
RUN yarn install
RUN yarn build
RUN go build -ldflags="-s -w" -o /bin/front ./cmd/app

## Stage 2 - Application Deploy
FROM debian:buster-slim as deploy

WORKDIR /bin/
COPY --from=build /bin/front .

ENV FRONT_ADDR 0.0.0.0
ENV FRONT_PORT 3001

EXPOSE 3001
CMD bash -c '/bin/front'

# sudo docker build -f ./front/Dockerfile.mcwebconsolefront -t mc-web-console-front:latest .
# sudo docker run --rm -p 3001:3001 mc-web-console-front:latest