## Stage 1 - Go Build Env
FROM golang:1.23-alpine AS build

RUN apk add --no-cache gcc libc-dev musl-dev curl npm wget
RUN npm install --global yarn

RUN mkdir -p /util
WORKDIR /util
RUN wget https://github.com/gobuffalo/cli/releases/download/v0.18.14/buffalo_0.18.14_Linux_x86_64.tar.gz \
    && tar -xvzf buffalo_0.18.14_Linux_x86_64.tar.gz \
    && mv buffalo /usr/local/bin/buffalo \
    && rm buffalo_0.18.14_Linux_x86_64.tar.gz

ENV GOPROXY http://proxy.golang.org
ENV CGO_ENABLED 1

RUN mkdir -p /src/mc-web-console-front
WORKDIR /src/mc-web-console-front
ADD ./front .

RUN go mod download
RUN npm install
RUN yarn install
RUN buffalo build --static -o /bin/front

## Stage 2 - Application Deploy
FROM debian:buster-slim as deploy

WORKDIR /bin/
COPY --from=build /bin/front .

ENV FRONT_ADDR 0.0.0.0
ENV FRONT_PORT 3001

EXPOSE 3001
CMD bash -c '/bin/front'

# sudo docker build -f ./front/Dockerfile.mcwebconsolefront -t mc-web-console-front:latest .
# sudo docker run --rm -p 3001:3001 mc-web-console-front:latest