package mciammanager

var (
	Alive                                           = "/alive"
	AliveAdmin                                      = "/alive/admin"
	AliveOperator                                   = "/alive/operator"
	AliveViewer                                     = "/alive/viewer"
	Getcerts                                        = "/api/auth/certs"
	Login                                           = "/api/auth/login"
	Loginrefresh                                    = "/api/auth/login/refresh"
	Logout                                          = "/api/auth/logout"
	Getuserinfo                                     = "/api/auth/userinfo"
	Getusevalidate                                  = "/api/auth/validate"
	Getprojectlist                                  = "/api/prj"
	Createproject                                   = "/api/prj"
	Deleteprojectbyid                               = "/api/prj/project/id/{projectId}"
	Getprojectbyid                                  = "/api/prj/project/id/{projectId}"
	Updateprojectbyid                               = "/api/prj/project/id/{projectId}"
	Searchprojectsbyname                            = "/api/prj/project/{projectName}"
	Getrolelist                                     = "/api/role"
	Createrole                                      = "/api/role"
	Deleterolebyid                                  = "/api/role/role/id/{roleId}"
	Getrolebyid                                     = "/api/role/role/id/{roleId}"
	Updaterolebyid                                  = "/api/role/role/id/{roleId}"
	Searchrolesbyname                               = "/api/role/role/{roleName}"
	Securitykey                                     = "/api/sts/securitykey"
	Syncprojectlistwithmcinfra                      = "/api/tool/mcinfra/sync"
	Getworkspacelist                                = "/api/ws"
	Createworkspace                                 = "/api/ws"
	Deleteworkspacebyid                             = "/api/ws/workspace/id/{workspaceId}"
	Getworkspacebyid                                = "/api/ws/workspace/id/{workspaceId}"
	Updateworkspacebyid                             = "/api/ws/workspace/id/{workspaceId}"
	Searchworkspacesbyname                          = "/api/ws/workspace/{workspaceName}"
	Getwpmappinglistorderbyworkspace                = "/api/wsprj"
	Createwpmapping                                 = "/api/wsprj"
	Updatewpmappings                                = "/api/wsprj"
	Getwpmappinglistbyworkspaceid                   = "/api/wsprj/workspace/id/{workspaceId}"
	Deleteworkspaceprojectmappingbyid               = "/api/wsprj/workspace/id/{workspaceId}/project/id/{projectId}"
	Getworkspaceuserrolemappinglistorderbyworkspace = "/api/wsuserrole"
	Createworkspaceuserrolemappingbyname            = "/api/wsuserrole"
	Getworkspaceuserrolemappinglistbyuserid         = "/api/wsuserrole/user/id/{userId}"
	Getworkspaceuserrolemappinglistbyworkspaceid    = "/api/wsuserrole/workspace/id/{workspaceId}"
	Deleteworkspaceuserrolemapping                  = "/api/wsuserrole/workspace/id/{workspaceId}/user/id/{userId}"
	Getworkspaceuserrolemappingbyid                 = "/api/wsuserrole/workspace/id/{workspaceId}/user/id/{userId}"
)
